/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ControlInterface;
import Controlador.Controler;
import Modelo.ModelInterface;
import Modelo.PackPiezas;
import Modelo.Tablero;

import javax.swing.*;
import java.awt.*;
import java.util.Calendar;

/**
 *
 * @author dbq560
 */
public class Seleccionador extends javax.swing.JFrame {

    Calendar tarda = Calendar.getInstance();
    /**
     * Creates new form Mesa
     */
    public Seleccionador() {
        initComponents();
        this.setResizable(false);
        modelo = new Tablero();
        controler = new Controler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        JLabel jLabel4 = new JLabel();
        JLabel jLabel5 = new JLabel();
        JLabel jLabel7 = new JLabel();
        JLabel jLabel8 = new JLabel();
        jtf_reinas = new javax.swing.JTextField();
        jtf_alfiles = new javax.swing.JTextField();
        jtf_torres = new javax.swing.JTextField();
        jtf_lanceros = new javax.swing.JTextField();
        jtf_halcones = new javax.swing.JTextField();
        JButton jtf_iniciar = new JButton();
        JLabel jLabel9 = new JLabel();
        jtf_lenght_table = new javax.swing.JTextField();
        tiempo = new javax.swing.JLabel();
        tiempo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Piezas de tablero");

        jLabel2.setText("Reinas:");

        jLabel4.setText("Alfiles");

        jLabel5.setText("Torres:");

        jLabel7.setText("Lanceros:");

        jLabel8.setText("Halcones:");

        jtf_reinas.setText("0");

        jtf_alfiles.setText("0");

        jtf_torres.setText("0");

        jtf_lanceros.setText("0");

        jtf_halcones.setText("0");

        jtf_iniciar.setText("Iniciar");
        jtf_iniciar.addActionListener(this::jtf_iniciarActionPerformed);

        jLabel9.setFont(new java.awt.Font("Times New Roman", Font.BOLD, 14)); // NOI18N
        jLabel9.setText("Tamaño del tablero");

        jtf_lenght_table.setText("0");
        jtf_lenght_table.setToolTipText("23");

        tiempo.setText("Acabado en: ");
        tiempo.setVisible(false);

        tiempo.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jtf_iniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jtf_lenght_table, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_halcones)
                                    .addComponent(jtf_lanceros)
                                    .addComponent(jtf_torres)
                                    .addComponent(jtf_alfiles)
                                    .addComponent(jtf_reinas, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tiempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiempo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jtf_lenght_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_reinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_alfiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_torres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_lanceros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtf_halcones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tiempo)
                    .addComponent(tiempo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(jtf_iniciar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_iniciarActionPerformed
        Reloj reloj = new Reloj();
        try {
            int lenght_table = Integer.parseInt(jtf_lenght_table.getText());

            int reinas = Integer.parseInt(jtf_reinas.getText());
            int alfiles = Integer.parseInt(jtf_alfiles.getText());
            int torres = Integer.parseInt(jtf_torres.getText());
            int lanceros = Integer.parseInt(jtf_lanceros.getText());
            int halcones = Integer.parseInt(jtf_halcones.getText());

            Mesa mesa = new Mesa(lenght_table);
            modelo = new Tablero(lenght_table);
            controler = new Controler(lenght_table);

            Vista.Tablero tablero = new Vista.Tablero(modelo);
            PackPiezas piezas = modelo.getPack(reinas, alfiles, torres, halcones, lanceros);
            mesa.add(tablero);

            long tardo = tarda.getTimeInMillis();
            reloj.Contar();
            //try {
            if (!controler.colocarPiezas(piezas.getPiezas())) {
                JOptionPane.showMessageDialog(null, "No hay solución para el problema");
            } else{
                tablero.repaint();
            }
            /*} catch (InterruptedException ex) {
                Logger.getLogger(Seleccionador.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            reloj.Detener();
            String conv = String.valueOf(tardo);
            tiempo1.setText(reloj.getTiempo() + "." + conv.substring(0, 4));
            tiempo.setVisible(true);
            tiempo1.setVisible(true);
            mesa.setVisible(true);
        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "Introduce valores numéricos");
        }
    }//GEN-LAST:event_jtf_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccionador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Seleccionador().setVisible(true));
    }

    private ModelInterface modelo;
    private ControlInterface controler;
    private javax.swing.JTextField jtf_alfiles;
    private javax.swing.JTextField jtf_halcones;
    private javax.swing.JTextField jtf_lanceros;
    private javax.swing.JTextField jtf_reinas;
    private javax.swing.JTextField jtf_lenght_table;
    private javax.swing.JTextField jtf_torres;
    private javax.swing.JLabel tiempo;
    private javax.swing.JLabel tiempo1;
    // End of variables declaration//GEN-END:variables
}
